---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: gosigar
  path: /go/src/github.com/cloudfoundry/gosigar

run:
  path: /go/src/github.com/cloudfoundry/gosigar/ci/tasks/test-unit.sh
